name: habit_tracker
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_spinkit: ^5.1.0
  table_calendar: ^3.0.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true